ietf-wg-masque/draft-ietf-masque-connect-udp

draft-ietf-masque-connect-udp.md
=> Can proceed without datagram

draft-ietf-masque-connect-udp.md
=> Clarify socket lifetime

draft-ietf-masque-connect-udp.md
This PR pairs with the corresponding HTTP Datagram PR:
https://github.com/ietf-wg-masque/draft-ietf-masque-h3-datagram/pull/91
[Rendered view of this PR here](https://ietf-wg-masque.github.io/draft-ietf-masque-connect-udp/reworked_h3dgram_ext/draft-ietf-masque-connect-udp.html).
=> React to HTTP Datagram extensibility rework

draft-ietf-masque-connect-udp.md
=> Rename token to connect-udp

draft-ietf-masque-connect-udp.md
This PR represents the consensus of the 2021 MASQUE Design Team.
[Rendered view of this PR](https://ietf-wg-masque.github.io/draft-ietf-masque-connect-udp/2021_design_team_consensus/draft-ietf-masque-connect-udp.html).
[Rendered diff with the editor's copy](https://www.ietf.org/rfcdiff?url1=https://ietf-wg-masque.github.io/draft-ietf-masque-connect-udp/draft-ietf-masque-connect-udp.txt&url2=https://ietf-wg-masque.github.io/draft-ietf-masque-connect-udp/2021_design_team_consensus/draft-ietf-masque-connect-udp.txt).
cc @afrind @LPardue @MikeBishop @martinthomson @vasilvv @ekr @achernya @bemasc @tfpauly @ihlar
Fixes #71 
Fixes #72
=> CONNECT-UDP: 2021 Design Team Consensus

draft-ietf-masque-connect-udp.md
=> Remove introspection ban

draft-ietf-masque-connect-udp.md
=> Do not force ordering for inactivity close

draft-ietf-masque-connect-udp.md
=> Clarify performance over h3

draft-ietf-masque-connect-udp.md
=> Don't fragment

draft-ietf-masque-connect-udp.md
=> Close stream on ICMP destination unreachable

draft-ietf-masque-connect-udp.md
=> Tighten rules around URI template

draft-ietf-masque-connect-udp.md
=> Switch to GET for HTTP/1.x

draft-ietf-masque-connect-udp.md
=> Switch to well-known URI

draft-ietf-masque-connect-udp.md
=> Improve abstract

draft-ietf-masque-connect-udp.md
=> Tighten definition of proxy

draft-ietf-masque-connect-udp.md
=> A URI Template

draft-ietf-masque-connect-udp.md
=> No request requests

draft-ietf-masque-connect-udp.md
=> No HTTP payload

draft-ietf-masque-connect-udp.md
=> Header fields, sure

draft-ietf-masque-connect-udp.md
=> Connections options are case insensitive

draft-ietf-masque-connect-udp.md
=> Point out extended connect requirements

draft-ietf-masque-connect-udp.md
=> fix dupe text

draft-ietf-masque-connect-udp.md
=> Packets contain frames

draft-ietf-masque-connect-udp.md
=> Remove normative text from security considerations

draft-ietf-masque-connect-udp.md
=> Add pointer to HTTP-DGRAM security considerations

draft-ietf-masque-connect-udp.md
=> Explain 65527

draft-ietf-masque-connect-udp.md
=> Cut up long sentence

draft-ietf-masque-connect-udp.md
=> Use bullets for URI template requirements

draft-ietf-masque-connect-udp.md
=> Ediorial tweak 131

draft-ietf-masque-connect-udp.md
=> Editorial 130

draft-ietf-masque-connect-udp.md
=> Editorial tweak

draft-ietf-masque-connect-udp.md
=> Provide more security guidance

draft-ietf-masque-connect-udp.md
=> More Proxy-Status

draft-ietf-masque-connect-udp.md
=> Add reference for VLI

draft-ietf-masque-connect-udp.md
=> Clarify Capdule Protocol mention

draft-ietf-masque-connect-udp.md
This PR is purely editorial and was made by cherry-picking most of @mnot's great work in #157.
=> Editorial PR based on Mark's work

draft-ietf-masque-connect-udp.md
=> Explain choice of GET in h1

draft-ietf-masque-connect-udp.md
=> Do not accidentally disallow multiple connection headers

draft-ietf-masque-connect-udp.md
=> Do not accidentally prevent offering multiple upgrade tokens

draft-ietf-masque-connect-udp.md
=> Clarify that template variables are allowed in query

draft-ietf-masque-connect-udp.md
=> Remove confusing paragraph

draft-ietf-masque-connect-udp.md
=> Remove caching text

draft-ietf-masque-connect-udp.md
=> Remove unnecessary absolute h1 requirement

draft-ietf-masque-connect-udp.md
=> Clarify that intermediaries can convert between versions

draft-ietf-masque-connect-udp.md
=> Specifically point out Proxy-Status dns_error

draft-ietf-masque-connect-udp.md
Nit from the AD review.
Reading this sentence, it took me a moment to figure out if we were talking about config on the client or the on the proxy.
=> clarify whose config

draft-ietf-masque-connect-udp.md
From AD Review:
Expand the acronym and add a (normative!) reference.
=> reference to ECN

draft-ietf-masque-connect-udp.md
PR in response to Christer's GENART review -- [email on list](https://mailarchive.ietf.org/arch/msg/masque/WCKDuo8LTi4etwj2YWL_ziEViHY/)
=> Comments from Christer's GENART review

draft-ietf-masque-connect-udp.md
This PR addresses the DISCUSS component of [Zahed's review](https://mailarchive.ietf.org/arch/msg/masque/jwDJ2-_e4EzHI_MIVHzKs3kVRNQ/). The COMMENT component of that review will be addressed in a subsequent PR.
=> Clarify handling of malformed requests over h1

draft-ietf-masque-connect-udp.md
This was prompted by [Erik's review](https://mailarchive.ietf.org/arch/msg/masque/xv1wwfAIiZAUwqkZAMce-cjfszA/).
=> Add security guidance
